// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AlibabaOutlined: typeof import('@ant-design/icons-vue')['AlibabaOutlined']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    DeleteTwoTone: typeof import('@ant-design/icons-vue')['DeleteTwoTone']
    EditTwoTone: typeof import('@ant-design/icons-vue')['EditTwoTone']
    GithubOutlined: typeof import('@ant-design/icons-vue')['GithubOutlined']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    MyBreadcrumb: typeof import('./src/components/MyBreadcrumb/index.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader/index.vue')['default']
    MyRouteTag: typeof import('./src/components/MyRouteTag/index.vue')['default']
    PlusCircleOutlined: typeof import('@ant-design/icons-vue')['PlusCircleOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    QuestionCircleOutlined: typeof import('@ant-design/icons-vue')['QuestionCircleOutlined']
    RedoOutlined: typeof import('@ant-design/icons-vue')['RedoOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutlined: typeof import('@ant-design/icons-vue')['SearchOutlined']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
