// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AlibabaOutlined: typeof import('@ant-design/icons-vue')['AlibabaOutlined']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AreaServer: typeof import('./src/components/AreaServer/index.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    BulbOutlined: typeof import('@ant-design/icons-vue')['BulbOutlined']
    ChoiceSkill: typeof import('./src/components/ChoiceSkill/index.vue')['default']
    ClusterOutlined: typeof import('@ant-design/icons-vue')['ClusterOutlined']
    DashboardTwoTone: typeof import('@ant-design/icons-vue')['DashboardTwoTone']
    GithubOutlined: typeof import('@ant-design/icons-vue')['GithubOutlined']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    MyBreadcrumb: typeof import('./src/components/MyBreadcrumb/index.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader/index.vue')['default']
    MyRouteTag: typeof import('./src/components/MyRouteTag/index.vue')['default']
    QueryFooter: typeof import('./src/components/QueryFooter/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillTable: typeof import('./src/components/SkillTable/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TeamOutlined: typeof import('@ant-design/icons-vue')['TeamOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
